// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  same54Sidebar: [{type: 'autogenerated', dirName: 'same54'}],
  pic32bz6Sidebar: [{type: 'autogenerated', dirName: 'pic32bz6'}],
  appendicesSidebar: [{type: 'autogenerated', dirName: 'appendices'}],
};

export default sidebars;
